CREATE TABLE books
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn               VARCHAR(255) UNIQUE                     NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    author             VARCHAR(255)                            NOT NULL,
    price              BIGINT                                  NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    version            INTEGER                                 NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE vouchers
(
    id               BIGSERIAL PRIMARY KEY,
    code             VARCHAR(255) NOT NULL UNIQUE,
    type             VARCHAR(50)  NOT NULL,
    value            BIGINT       NOT NULL,
    quantity         INTEGER      NOT NULL,
    start_date        TIMESTAMP    NOT NULL,
    end_date          TIMESTAMP    NOT NULL,
    created_by        VARCHAR(255) NOT NULL,
    created_date      TIMESTAMP    NOT NULL,
    last_modified_by   VARCHAR(255) NOT NULL,
    last_modified_date TIMESTAMP    NOT NULL,
    status           INTEGER,
    version          int          NOT NULL
);

CREATE TABLE reviews
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_id          BIGINT,
    rate             INTEGER,
    comment          VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

CREATE TABLE orders (
                        id UUID PRIMARY KEY,
                        user_id VARCHAR(255) NOT NULL,
                        status VARCHAR(255) NOT NULL,
                        created_date TIMESTAMP,
                        last_modified_by TIMESTAMP,
                        last_modified_date TIMESTAMP,
                        version INT
);

CREATE TABLE order_details (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               book_id BIGINT NOT NULL,
                               price BIGINT NOT NULL,
                               quantity INT NOT NULL,
                               order_id UUID,
                               CONSTRAINT pk_order_details PRIMARY KEY (id)
);

ALTER TABLE order_details
    ADD CONSTRAINT FK_ORDER_DETAIL_ON_BOOK FOREIGN KEY (book_id) REFERENCES books(id);
ALTER TABLE order_details
    ADD CONSTRAINT FK_ORDER_DETAIL_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders(id);