CREATE TABLE books
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn               VARCHAR(255) UNIQUE                     NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    author             VARCHAR(255)                            NOT NULL,
    price              BIGINT                                  NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    version            INTEGER                                 NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE vouchers
(
    id               BIGSERIAL PRIMARY KEY,
    code             VARCHAR(255) NOT NULL UNIQUE,
    type             VARCHAR(50)  NOT NULL,
    value            BIGINT       NOT NULL,
    quantity         INTEGER      NOT NULL,
    start_date        TIMESTAMP    NOT NULL,
    end_date          TIMESTAMP    NOT NULL,
    created_by        VARCHAR(255) NOT NULL,
    created_date      TIMESTAMP    NOT NULL,
    last_modified_by   VARCHAR(255) NOT NULL,
    last_modified_date TIMESTAMP    NOT NULL,
    status           INTEGER,
    version          int          NOT NULL
);

CREATE TABLE reviews
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_id          BIGINT,
    rate             INTEGER,
    comment          VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);