server:
  port: 8001

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_backend
    username: user
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bookstore
  jpa:
    hibernate:
      ddl-auto: update